
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Tables.Core
{
    public sealed partial class EntityGroupTable : LuBan.Runtime.BeanBase
    {
        public EntityGroupTable(int ID, string Name, float ReleaseInterval, int Capacity, float ExpireTime, int Priority) 
        {
            this.ID = ID;
            this.Name = Name;
            this.ReleaseInterval = ReleaseInterval;
            this.Capacity = Capacity;
            this.ExpireTime = ExpireTime;
            this.Priority = Priority;
            PostInit();
        }

        public EntityGroupTable(JSONNode _buf)
        {
            { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["ReleaseInterval"].IsNumber) { throw new SerializationException(); }  ReleaseInterval = _buf["ReleaseInterval"]; }
            { if(!_buf["Capacity"].IsNumber) { throw new SerializationException(); }  Capacity = _buf["Capacity"]; }
            { if(!_buf["ExpireTime"].IsNumber) { throw new SerializationException(); }  ExpireTime = _buf["ExpireTime"]; }
            { if(!_buf["Priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["Priority"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static EntityGroupTable DeserializeEntityGroupTable(JSONNode _buf)
        {
            return new Tables.Core.EntityGroupTable(_buf);
        }

        public int ID { private set; get; }
        public string Name { private set; get; }
        public float ReleaseInterval { private set; get; }
        public int Capacity { private set; get; }
        public float ExpireTime { private set; get; }
        public int Priority { private set; get; }
        public const int __ID__ = -1275004776;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "ID:" + ID + ","
            + "Name:" + Name + ","
            + "ReleaseInterval:" + ReleaseInterval + ","
            + "Capacity:" + Capacity + ","
            + "ExpireTime:" + ExpireTime + ","
            + "Priority:" + Priority + ","
            + "}";
        }

        partial void PostInit();
    }
}
