
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Tables.Core
{
    public sealed partial class SoundGroupTable : LuBan.Runtime.BeanBase
    {
        public SoundGroupTable(int ID, string Name, int SoundAgentCount, bool AvoidBeingReplacedBySamePriority, bool Mute, float Volume) 
        {
            this.ID = ID;
            this.Name = Name;
            this.SoundAgentCount = SoundAgentCount;
            this.AvoidBeingReplacedBySamePriority = AvoidBeingReplacedBySamePriority;
            this.Mute = Mute;
            this.Volume = Volume;
            PostInit();
        }

        public SoundGroupTable(JSONNode _buf)
        {
            { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["SoundAgentCount"].IsNumber) { throw new SerializationException(); }  SoundAgentCount = _buf["SoundAgentCount"]; }
            { if(!_buf["AvoidBeingReplacedBySamePriority"].IsBoolean) { throw new SerializationException(); }  AvoidBeingReplacedBySamePriority = _buf["AvoidBeingReplacedBySamePriority"]; }
            { if(!_buf["Mute"].IsBoolean) { throw new SerializationException(); }  Mute = _buf["Mute"]; }
            { if(!_buf["Volume"].IsNumber) { throw new SerializationException(); }  Volume = _buf["Volume"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static SoundGroupTable DeserializeSoundGroupTable(JSONNode _buf)
        {
            return new Tables.Core.SoundGroupTable(_buf);
        }

        public int ID { private set; get; }
        public string Name { private set; get; }
        public int SoundAgentCount { private set; get; }
        public bool AvoidBeingReplacedBySamePriority { private set; get; }
        public bool Mute { private set; get; }
        public float Volume { private set; get; }
        public const int __ID__ = 1646194296;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "ID:" + ID + ","
            + "Name:" + Name + ","
            + "SoundAgentCount:" + SoundAgentCount + ","
            + "AvoidBeingReplacedBySamePriority:" + AvoidBeingReplacedBySamePriority + ","
            + "Mute:" + Mute + ","
            + "Volume:" + Volume + ","
            + "}";
        }

        partial void PostInit();
    }
}
