
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Tables.Core
{
    public sealed partial class UIGroupTable : LuBan.Runtime.BeanBase
    {
        public UIGroupTable(int ID, string Name, int Depth) 
        {
            this.ID = ID;
            this.Name = Name;
            this.Depth = Depth;
            PostInit();
        }

        public UIGroupTable(JSONNode _buf)
        {
            { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["Depth"].IsNumber) { throw new SerializationException(); }  Depth = _buf["Depth"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static UIGroupTable DeserializeUIGroupTable(JSONNode _buf)
        {
            return new Tables.Core.UIGroupTable(_buf);
        }

        public int ID { private set; get; }
        public string Name { private set; get; }
        /// <summary>
        /// 每个组的起始Order,用于控制显示顺序
        /// </summary>
        public int Depth { private set; get; }
        public const int __ID__ = 1642640617;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "ID:" + ID + ","
            + "Name:" + Name + ","
            + "Depth:" + Depth + ","
            + "}";
        }

        partial void PostInit();
    }
}
