
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Tables
{
    public sealed partial class CameraViewTable : LuBan.Runtime.BeanBase
    {
        public CameraViewTable(int ID, UnityEngine.Vector3 FollowOffset, UnityEngine.Vector3 AimOffset) 
        {
            this.ID = ID;
            this.FollowOffset = FollowOffset;
            this.AimOffset = AimOffset;
            PostInit();
        }

        public CameraViewTable(JSONNode _buf)
        {
            { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
            { if(!_buf["FollowOffset"].IsObject) { throw new SerializationException(); }  FollowOffset = ExternalTypeUtil.NewVector3(vec3.Deserializevec3(_buf["FollowOffset"]));  }
            { if(!_buf["AimOffset"].IsObject) { throw new SerializationException(); }  AimOffset = ExternalTypeUtil.NewVector3(vec3.Deserializevec3(_buf["AimOffset"]));  }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static CameraViewTable DeserializeCameraViewTable(JSONNode _buf)
        {
            return new Tables.CameraViewTable(_buf);
        }

        public int ID { private set; get; }
        /// <summary>
        /// 跟随偏移
        /// </summary>
        public UnityEngine.Vector3 FollowOffset { private set; get; }
        public UnityEngine.Vector3 AimOffset { private set; get; }
        public const int __ID__ = 1389108475;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "ID:" + ID + ","
            + "FollowOffset:" + FollowOffset + ","
            + "AimOffset:" + AimOffset + ","
            + "}";
        }

        partial void PostInit();
    }
}
