
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Tables
{
    public sealed partial class LevelTable : LuBan.Runtime.BeanBase
    {
        public LevelTable(int ID, string LvPfbName, int InitMoney, int MoneyColorId, string LvDisplayName) 
        {
            this.ID = ID;
            this.LvPfbName = LvPfbName;
            this.InitMoney = InitMoney;
            this.MoneyColorId = MoneyColorId;
            this.LvDisplayName = LvDisplayName;
            PostInit();
        }

        public LevelTable(JSONNode _buf)
        {
            { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
            { if(!_buf["LvPfbName"].IsString) { throw new SerializationException(); }  LvPfbName = _buf["LvPfbName"]; }
            { if(!_buf["InitMoney"].IsNumber) { throw new SerializationException(); }  InitMoney = _buf["InitMoney"]; }
            { if(!_buf["MoneyColorId"].IsNumber) { throw new SerializationException(); }  MoneyColorId = _buf["MoneyColorId"]; }
            { if(!_buf["LvDisplayName"].IsString) { throw new SerializationException(); }  LvDisplayName = _buf["LvDisplayName"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static LevelTable DeserializeLevelTable(JSONNode _buf)
        {
            return new Tables.LevelTable(_buf);
        }

        public int ID { private set; get; }
        /// <summary>
        /// 关卡prefab名
        /// </summary>
        public string LvPfbName { private set; get; }
        /// <summary>
        /// 玩家初始钱数
        /// </summary>
        public int InitMoney { private set; get; }
        /// <summary>
        /// 取值1-6
        /// </summary>
        public int MoneyColorId { private set; get; }
        /// <summary>
        /// 关卡显示名(多语言)
        /// </summary>
        public string LvDisplayName { private set; get; }
        public const int __ID__ = 1907277267;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "ID:" + ID + ","
            + "LvPfbName:" + LvPfbName + ","
            + "InitMoney:" + InitMoney + ","
            + "MoneyColorId:" + MoneyColorId + ","
            + "LvDisplayName:" + LvDisplayName + ","
            + "}";
        }

        partial void PostInit();
    }
}
