
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Tables
{
    public sealed partial class ColorTable : LuBan.Runtime.BeanBase
    {
        public ColorTable(int Id, string ColorHex) 
        {
            this.Id = Id;
            this.ColorHex = ColorHex;
            PostInit();
        }

        public ColorTable(JSONNode _buf)
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["ColorHex"].IsString) { throw new SerializationException(); }  ColorHex = _buf["ColorHex"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static ColorTable DeserializeColorTable(JSONNode _buf)
        {
            return new Tables.ColorTable(_buf);
        }

        public int Id { private set; get; }
        public string ColorHex { private set; get; }
        public const int __ID__ = -1305100972;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ColorHex:" + ColorHex + ","
            + "}";
        }

        partial void PostInit();
    }
}
