
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Tables
{
    public sealed partial class CombatUnitTable : LuBan.Runtime.BeanBase
    {
        public CombatUnitTable(int ID, string PrefabName, float AttackRadius, float MoveSpeed, int Hp, int Damage, int MaxAttackCount) 
        {
            this.ID = ID;
            this.PrefabName = PrefabName;
            this.AttackRadius = AttackRadius;
            this.MoveSpeed = MoveSpeed;
            this.Hp = Hp;
            this.Damage = Damage;
            this.MaxAttackCount = MaxAttackCount;
            PostInit();
        }

        public CombatUnitTable(JSONNode _buf)
        {
            { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
            { if(!_buf["PrefabName"].IsString) { throw new SerializationException(); }  PrefabName = _buf["PrefabName"]; }
            { if(!_buf["AttackRadius"].IsNumber) { throw new SerializationException(); }  AttackRadius = _buf["AttackRadius"]; }
            { if(!_buf["MoveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["MoveSpeed"]; }
            { if(!_buf["Hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["Hp"]; }
            { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
            { if(!_buf["MaxAttackCount"].IsNumber) { throw new SerializationException(); }  MaxAttackCount = _buf["MaxAttackCount"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static CombatUnitTable DeserializeCombatUnitTable(JSONNode _buf)
        {
            return new Tables.CombatUnitTable(_buf);
        }

        public int ID { private set; get; }
        /// <summary>
        /// 预制体资源
        /// </summary>
        public string PrefabName { private set; get; }
        /// <summary>
        /// 攻击半径
        /// </summary>
        public float AttackRadius { private set; get; }
        /// <summary>
        /// 移动速度
        /// </summary>
        public float MoveSpeed { private set; get; }
        /// <summary>
        /// 默认血量
        /// </summary>
        public int Hp { private set; get; }
        /// <summary>
        /// 伤害
        /// </summary>
        public int Damage { private set; get; }
        /// <summary>
        /// 单次攻击敌人个数
        /// </summary>
        public int MaxAttackCount { private set; get; }
        public const int __ID__ = 364351117;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "ID:" + ID + ","
            + "PrefabName:" + PrefabName + ","
            + "AttackRadius:" + AttackRadius + ","
            + "MoveSpeed:" + MoveSpeed + ","
            + "Hp:" + Hp + ","
            + "Damage:" + Damage + ","
            + "MaxAttackCount:" + MaxAttackCount + ","
            + "}";
        }

        partial void PostInit();
    }
}
