
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Tables.Core
{
    public sealed partial class LanguagesTable : LuBan.Runtime.BeanBase
    {
        public LanguagesTable(int ID, string LanguageKey, string AssetName, string LanguageDisplay, string LanguageIcon) 
        {
            this.ID = ID;
            this.LanguageKey = LanguageKey;
            this.AssetName = AssetName;
            this.LanguageDisplay = LanguageDisplay;
            this.LanguageIcon = LanguageIcon;
            PostInit();
        }

        public LanguagesTable(JSONNode _buf)
        {
            { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
            { if(!_buf["LanguageKey"].IsString) { throw new SerializationException(); }  LanguageKey = _buf["LanguageKey"]; }
            { if(!_buf["AssetName"].IsString) { throw new SerializationException(); }  AssetName = _buf["AssetName"]; }
            { if(!_buf["LanguageDisplay"].IsString) { throw new SerializationException(); }  LanguageDisplay = _buf["LanguageDisplay"]; }
            { if(!_buf["LanguageIcon"].IsString) { throw new SerializationException(); }  LanguageIcon = _buf["LanguageIcon"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static LanguagesTable DeserializeLanguagesTable(JSONNode _buf)
        {
            return new Tables.Core.LanguagesTable(_buf);
        }

        public int ID { private set; get; }
        /// <summary>
        /// 多语言文件名
        /// </summary>
        public string LanguageKey { private set; get; }
        /// <summary>
        /// 多语言资源名(相对路径)
        /// </summary>
        public string AssetName { private set; get; }
        /// <summary>
        /// 用于显示的语言名
        /// </summary>
        public string LanguageDisplay { private set; get; }
        /// <summary>
        /// 语言图标
        /// </summary>
        public string LanguageIcon { private set; get; }
        public const int __ID__ = -621514311;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "ID:" + ID + ","
            + "LanguageKey:" + LanguageKey + ","
            + "AssetName:" + AssetName + ","
            + "LanguageDisplay:" + LanguageDisplay + ","
            + "LanguageIcon:" + LanguageIcon + ","
            + "}";
        }

        partial void PostInit();
    }
}
