
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Tables.Core
{
    public sealed partial class UITable : LuBan.Runtime.BeanBase
    {
        public UITable(int Id, int SortOrder, string UIPrefab, bool PauseCoveredUI, int UIGroupId, bool EscapeClose) 
        {
            this.Id = Id;
            this.SortOrder = SortOrder;
            this.UIPrefab = UIPrefab;
            this.PauseCoveredUI = PauseCoveredUI;
            this.UIGroupId = UIGroupId;
            this.EscapeClose = EscapeClose;
            PostInit();
        }

        public UITable(JSONNode _buf)
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["SortOrder"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["SortOrder"]; }
            { if(!_buf["UIPrefab"].IsString) { throw new SerializationException(); }  UIPrefab = _buf["UIPrefab"]; }
            { if(!_buf["PauseCoveredUI"].IsBoolean) { throw new SerializationException(); }  PauseCoveredUI = _buf["PauseCoveredUI"]; }
            { if(!_buf["UIGroupId"].IsNumber) { throw new SerializationException(); }  UIGroupId = _buf["UIGroupId"]; }
            { if(!_buf["EscapeClose"].IsBoolean) { throw new SerializationException(); }  EscapeClose = _buf["EscapeClose"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static UITable DeserializeUITable(JSONNode _buf)
        {
            return new Tables.Core.UITable(_buf);
        }

        public int Id { private set; get; }
        /// <summary>
        /// 显示顺序,相对于Group,每个Group间隔100
        /// </summary>
        public int SortOrder { private set; get; }
        public string UIPrefab { private set; get; }
        /// <summary>
        /// 同组界面被覆盖时是否隐藏
        /// </summary>
        public bool PauseCoveredUI { private set; get; }
        /// <summary>
        /// UI组Id
        /// </summary>
        public int UIGroupId { private set; get; }
        /// <summary>
        /// 返回键触发关闭界面
        /// </summary>
        public bool EscapeClose { private set; get; }
        public const int __ID__ = 1579139892;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SortOrder:" + SortOrder + ","
            + "UIPrefab:" + UIPrefab + ","
            + "PauseCoveredUI:" + PauseCoveredUI + ","
            + "UIGroupId:" + UIGroupId + ","
            + "EscapeClose:" + EscapeClose + ","
            + "}";
        }

        partial void PostInit();
    }
}
