
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;

namespace Hotfix.Config
{
    public partial class TablesComponent
    {

        internal Local.TbLocalization TbLocalization { private set; get; }

        internal Tables.TbAchievementConfig TbAchievementConfig { private set; get; }

        internal Tables.TbCameraViewTable TbCameraViewTable { private set; get; }

        internal Tables.TbColorTable TbColorTable { private set; get; }

        internal Tables.TbCombatUnitTable TbCombatUnitTable { private set; get; }

        internal Tables.TbLevelTable TbLevelTable { private set; get; }

        internal Tables.TbItemConfig TbItemConfig { private set; get; }

        internal Tables.TbSoundsConfig TbSoundsConfig { private set; get; }

        internal Tables.Core.TbEntityGroupTable TbEntityGroupTable { private set; get; }

        internal Tables.Core.TbLanguagesTable TbLanguagesTable { private set; get; }

        internal Tables.Core.TbSoundGroupTable TbSoundGroupTable { private set; get; }

        internal Tables.Core.TbUIGroupTable TbUIGroupTable { private set; get; }

        internal Tables.Core.TbUITable TbUITable { private set; get; }

        private ConfigComponent m_ConfigComponent;

        public void Init(ConfigComponent configComponent)
        {
            m_ConfigComponent = configComponent;
            configComponent.RemoveAllConfigs();
        }

        /// <summary>
        /// 是否加载完成
        /// </summary>
        public bool IsLoaded { get; private set; }

        /// <summary>
        /// 异步加载配置文件
        /// </summary>
        /// <param name="loader">加载器</param>
        public async System.Threading.Tasks.Task LoadAsync(System.Func<string, System.Threading.Tasks.Task<JSONNode>> loader)
        {
            if (IsLoaded)
            {
                return;
            }
            IsLoaded = false;
            m_ConfigComponent.RemoveAllConfigs();
            var loadTasks = new System.Collections.Generic.List<System.Threading.Tasks.Task>();
    
            TbLocalization = new Local.TbLocalization(() => loader("local_tblocalization"));
            loadTasks.Add(TbLocalization.LoadAsync());
            m_ConfigComponent.Add(nameof(Local.TbLocalization), TbLocalization);

            TbAchievementConfig = new Tables.TbAchievementConfig(() => loader("tables_tbachievementconfig"));
            loadTasks.Add(TbAchievementConfig.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.TbAchievementConfig), TbAchievementConfig);

            TbCameraViewTable = new Tables.TbCameraViewTable(() => loader("tables_tbcameraviewtable"));
            loadTasks.Add(TbCameraViewTable.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.TbCameraViewTable), TbCameraViewTable);

            TbColorTable = new Tables.TbColorTable(() => loader("tables_tbcolortable"));
            loadTasks.Add(TbColorTable.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.TbColorTable), TbColorTable);

            TbCombatUnitTable = new Tables.TbCombatUnitTable(() => loader("tables_tbcombatunittable"));
            loadTasks.Add(TbCombatUnitTable.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.TbCombatUnitTable), TbCombatUnitTable);

            TbLevelTable = new Tables.TbLevelTable(() => loader("tables_tbleveltable"));
            loadTasks.Add(TbLevelTable.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.TbLevelTable), TbLevelTable);

            TbItemConfig = new Tables.TbItemConfig(() => loader("tables_tbitemconfig"));
            loadTasks.Add(TbItemConfig.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.TbItemConfig), TbItemConfig);

            TbSoundsConfig = new Tables.TbSoundsConfig(() => loader("tables_tbsoundsconfig"));
            loadTasks.Add(TbSoundsConfig.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.TbSoundsConfig), TbSoundsConfig);

            TbEntityGroupTable = new Tables.Core.TbEntityGroupTable(() => loader("tables_core_tbentitygrouptable"));
            loadTasks.Add(TbEntityGroupTable.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.Core.TbEntityGroupTable), TbEntityGroupTable);

            TbLanguagesTable = new Tables.Core.TbLanguagesTable(() => loader("tables_core_tblanguagestable"));
            loadTasks.Add(TbLanguagesTable.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.Core.TbLanguagesTable), TbLanguagesTable);

            TbSoundGroupTable = new Tables.Core.TbSoundGroupTable(() => loader("tables_core_tbsoundgrouptable"));
            loadTasks.Add(TbSoundGroupTable.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.Core.TbSoundGroupTable), TbSoundGroupTable);

            TbUIGroupTable = new Tables.Core.TbUIGroupTable(() => loader("tables_core_tbuigrouptable"));
            loadTasks.Add(TbUIGroupTable.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.Core.TbUIGroupTable), TbUIGroupTable);

            TbUITable = new Tables.Core.TbUITable(() => loader("tables_core_tbuitable"));
            loadTasks.Add(TbUITable.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.Core.TbUITable), TbUITable);

    
            await System.Threading.Tasks.Task.WhenAll(loadTasks);
    
            Refresh();
            IsLoaded = true;
        }

        /// <summary>
        /// 设置本地化的适配器
        /// </summary>
        /// <param name="translator">适配器对象</param>
        /// <exception cref="InvalidOperationException">如果未加载完成将抛出此异常</exception>
        public void SetTranslateText(System.Func<string, string, string> translator)
        {
            if (IsLoaded == false)
            {
                throw new InvalidOperationException("Table is not loaded!");
            }
            TbLocalization.TranslateText(translator);
            TbAchievementConfig.TranslateText(translator);
            TbCameraViewTable.TranslateText(translator);
            TbColorTable.TranslateText(translator);
            TbCombatUnitTable.TranslateText(translator);
            TbLevelTable.TranslateText(translator);
            TbItemConfig.TranslateText(translator);
            TbSoundsConfig.TranslateText(translator);
            TbEntityGroupTable.TranslateText(translator);
            TbLanguagesTable.TranslateText(translator);
            TbSoundGroupTable.TranslateText(translator);
            TbUIGroupTable.TranslateText(translator);
            TbUITable.TranslateText(translator);
        }

        private void ResolveRef()
        {
            TbLocalization.ResolveRef(this);
            TbAchievementConfig.ResolveRef(this);
            TbCameraViewTable.ResolveRef(this);
            TbColorTable.ResolveRef(this);
            TbCombatUnitTable.ResolveRef(this);
            TbLevelTable.ResolveRef(this);
            TbItemConfig.ResolveRef(this);
            TbSoundsConfig.ResolveRef(this);
            TbEntityGroupTable.ResolveRef(this);
            TbLanguagesTable.ResolveRef(this);
            TbSoundGroupTable.ResolveRef(this);
            TbUIGroupTable.ResolveRef(this);
            TbUITable.ResolveRef(this);
        }
    
        public void Refresh()
        {
            PostInit();
            ResolveRef();
        }
    
        partial void PostInit();
    }
}
